matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      sudo: required

language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run test
  - npm run test:e2e
