# build is disabled because it expects MS Visual Studio solution file
build: off

version: '0.0.1.dev.{build}'

environment:
  nodejs_version: "6.9.1"
  apiUrl : "https://ci.appveyor.com/api"

install:
  - ps: $apiUrl
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
