# build is disabled because it expects MS Visual Studio solution file
build: off

version: '0.0.1.dev.{build}'

environment:
  nodejs_version: "6.9.0"
  apiUrl : "https://ci.appveyor.com/api"

cache:
  - node_modules -> package.json

install:
  - ps: $apiUrl
  - ps: Install-Product node $env:nodejs_version
  - npm install npm
  - .\node_modules\.bin\npm install
  - .\node_modules\.bin\npm run dist

test_script:
  - node --version
  - .\node_modules\.bin\npm --version
  - .\node_modules\.bin\npm test

artifacts:
  - path: 'dist\*.exe'
    name: dedop-studio-installer-exe
  - path: 'dist\*.zip'
    name: dedop-studio-installer-zip

deploy:
    # FTP deployment provider settings
  - provider: FTP
    protocol: ftp
    host: ftp.brockmann-consult.de
    username: dedop
    password:
      secure: GL7E4cOZi9mzFvaDMAVOaQ==
    artifact: dedop-studio-installer-exe
    folder: win64
    debug: true     # show complete FTP log
