build: off

branches:
  only:
    - master

skip_tags: true

environment:
  nodejs_version: "6.9.0"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm
  - .\node_modules\.bin\npm install
  - .\node_modules\.bin\npm run dist

test_script:
  - node --version
  - .\node_modules\.bin\npm --version
  - .\node_modules\.bin\npm test
  - .\node_modules\.bin\npm run test:e2e
